### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:3838

### ISSUE THREAD

**Issue by felloumi** [rstudio/proxyrec#11]
Hello,

We installed proxyrec in a mac desktop and run successfully the first step recording the load test:
 
proxyrec record -p 8602 -t 'http://discovery.nci.nih.gov:9090' > cdb-recording.txt
 
and we run our app “cellminercdb_test” using http://localhost:8602/cellminercdb_test and we recorded the requests in file cdb-recording.txt
 
Now performing the load test we got an error when running the proxyrec playback:
proxyrec playback cdb-recording.txt –t 'http://discovery.nci.nih.gov:9090' –c 20 –d '5min' -o 'loadtests'
 
Here is the message:
 
!!!!!!!!!!!!!!!!
 
0 succeeded, 7616 failed
7616 incidences of:
Error: connect ECONNREFUSED 127.0.0.1:3838
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:759:35)
    at tickOnSocket (_http_client.js:652:10)
    at onSocketNT (_http_client.js:682:5)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
---------------------------------------------
    at ClientRequest.onSocket (_http_client.js:670:11)
    at _http_agent.js:190:11
    at oncreate (_http_agent.js:236:5)
    at Agent.createSocket (_http_agent.js:223:5)
    at Agent.addRequest (_http_agent.js:183:10)
    at new ClientRequest (_http_client.js:271:16)
    at Object.request (http.js:39:10)
    at ShinyEvent.execute.Promise (/snapshot/proxyrec/lib/shiny-events.js:0)
    at Promise (<anonymous>)
 
 
Could you help us to solve this issue? Using the latest proxyrec from github gave the same error. Do we need to have port 3838 for shiny server?
 
Thanks,
 
Fathi

**Comment by slopp** [comment]
Can you supply the recording text file and one of the sample profile files?

Is the application restricted by authentication?

**Comment by felloumi** [comment]
No there is no authentication. Here are the requested files:

[cdb-recording.txt](https://github.com/rstudio/proxyrec/files/1402769/cdb-recording.txt)
[profile_0_2.txt](https://github.com/rstudio/proxyrec/files/1402771/profile_0_2.txt)

**Comment by jcheng5** [comment]
I think the problem is that you have the options coming after the filename:

```
proxyrec playback cdb-recording.txt –t 'http://discovery.nci.nih.gov:9090' –c 20 –d '5min' -o 'loadtests'
```

should be

```
proxyrec playback –t 'http://discovery.nci.nih.gov:9090' –c 20 –d '5min' -o 'loadtests' cdb-recording.txt
```

We should give you an error though (instead of silently ignoring everything after the filename).

**Comment by felloumi** [comment]
No the syntax  is correct.

Now I used  the latest proxy version with the following steps:

a- node lib/main.js record -p 8602 -t 'http://discovery.nci.nih.gov:9090' > cdb-recording-4.txt
b- testing the url: "http://localhost:8602/cellminercdb_test"
c- node lib/main.js playback cdb-recording-4.txt –t 'http://discovery.nci.nih.gov:9090' –c 1 –d '1min' -o 'loadtests4' --debug

I got the same error:
!/cellminercdb_test/
!/cellminercdb_test/
!/cellminercdb_test/
!/cellminercdb_test/
!

0 succeeded, 7500 failed
7500 incidences of:
Error: connect ECONNREFUSED 127.0.0.1:8602
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:773:35)
    at tickOnSocket (_http_client.js:638:10)
    at onSocketNT (_http_client.js:668:5)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
---------------------------------------------
    at ClientRequest.onSocket (_http_client.js:656:11)
    at handleSocketCreation_Inner (_http_agent.js:340:15)
    at oncreate (_http_agent.js:240:5)
    at Agent.createSocket (_http_agent.js:226:5)
    at Agent.addRequest (_http_agent.js:192:10)
    at new ClientRequest (_http_client.js:256:16)
    at Object.request (http.js:39:10)
    at Promise (/Users/elloumif/proxyrec/lib/shiny-events.js:240:28)
    at new Promise (<anonymous>)

After that I edited the file /lib/main.js to have
>>
.command("playback <file>", "Playback a run", yargs => {
    yargs.option("target", {
      alias: "t",
      describe: "Target URL",
      default: "http://discovery.nci.nih.gov:9090"
    });

>>

Now running the command again it seems working but waiting ....

node lib/main.js playback cdb-recording-4.txt –t 'http://discovery.nci.nih.gov:9090' –c 1 –d '1min' -o 'loadtests4' --debug
/cellminercdb_test/
/cellminercdb_test/_w_${WORKER}/shared/json2-min.js
/cellminercdb_test/_w_${WORKER}/shared/shiny.css
/cellminercdb_test/_w_${WORKER}/shared/shiny.min.js
/cellminercdb_test/_w_${WORKER}/shared/jquery.min.js
/cellminercdb_test/_w_${WORKER}/shared/selectize/css/selectize.bootstrap3.css
/cellminercdb_test/_w_${WORKER}/shared/selectize/js/selectize.min.js
/cellminercdb_test/_w_${WORKER}/shared/bootstrap/css/bootstrap.min.css
/cellminercdb_test/_w_${WORKER}/shared/bootstrap/shim/html5shiv.min.js
/cellminercdb_test/_w_${WORKER}/shared/bootstrap/js/bootstrap.min.js
/cellminercdb_test/_w_${WORKER}/shared/bootstrap/shim/respond.min.js
/cellminercdb_test/_w_${WORKER}/__assets__/shiny-server-client.min.js
/cellminercdb_test/_w_${WORKER}/__assets__/sockjs-0.3.4.min.js
/cellminercdb_test/_w_${WORKER}/__assets__/shiny-server.css
/cellminercdb_test/_w_${WORKER}/files/rcellminer_screenshot_anno.png
/cellminercdb_test/_w_${WORKER}/__token__?_=1508677344898
/cellminercdb_test/__sockjs__/n=${ROBUST_ID}/t=${TOKEN}/w=${WORKER}/s=0/info
/cellminercdb_test/__sockjs__/n=${ROBUST_ID}/t=${TOKEN}/w=${WORKER}/s=0/693/bznadq93/xhr_streaming
^C  ##  after waiting 10 minutes 

0 succeeded, 0 failed

Any suggestions?

Thanks.

**Comment by slopp** [comment]
At this time proxyrec requires that the client and server communicate via websockets. Your logs indicate that SockJS was falling back to xhr-streaming. There are a few reasons this fallback would have occurred (if websockets are not supported by either the client or the server). You could potentially try using a newer browser to record the test. Adding support for non-websocket traffic is on the roadmap.

**Comment by felloumi** [comment]
Ok, I enabled websocket and run like previously. Now I have a new record file cdb-cellminercdb-5.txt. It started working however I got error at the end:

0 succeeded, 6 failed
6 incidences of:
Error: Messages do not match!

Expected:
a["13#0|m|{\\"errors...

Actual:
a["13#0|m|{\\"errors...
    at ShinyWSReceiveEvent.execute (/Users/elloumif/proxyrec/lib/shiny-events.js:510:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Here are the details:
[cdb-recording-5.txt](https://github.com/rstudio/proxyrec/files/1412039/cdb-recording-5.txt)
[playback_output.txt](https://github.com/rstudio/proxyrec/files/1412042/playback_output.txt)

**Comment by bogdanrau** [comment]
Have you made any headway on this @felloumi ? Seems like I'm running into the same problem. Are you running SSP or RSC?
