### ISSUE TITLE
(Playback) Error: Messages do not match!

### ISSUE THREAD

**Issue by bogdanrau** [rstudio/proxyrec#12]
I recorded a simple test that just loads the application waits a few seconds, then closes the browser. I keep getting a failure at line 77 of playback. I've copied the specific error below, with the last line in the output as well. It seems like that's the line that it fails.

```
a["0#0|m|{\\"config\\":{\\"workerId\\":\\"5ea5af74\\",\\"sessionId\\":\\"${SESSION}\\",\\"user\\":null}}"]

0 succeeded, 2 failed
2 incidences of:
Error: Messages do not match!

Expected:
a["0#0|m|{\\"config\...

Actual:
a["0#0|m|{\\"config\...
    at ShinyWSInitReceiveEvent.execute (/home/o771465/proxyrec/lib/shiny-events.js:510:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

```
74	2017-12-12T23:13:39.547Z	2	WS_RECV	0
75	2017-12-12T23:13:39.557Z	1	WS_SEND	9
76	2017-12-12T23:13:39.560Z	0	WS_SEND	2
77	2017-12-12T23:13:39.617Z	56	WS_RECV_INIT	0
# Failure
# Job finished in 18363ms
```

And here is the snippet from the actual playback file
```
{"type":"WS_RECV_INIT","created":"2017-12-12T22:23:12.604Z","message":"a[\"0#0|m|{\\\\\"config\\\\\":{\\\\\"workerId\\\\\":\\\\\"5ea5af74\\\\\",\\\\\"sessionId\\\\\":\\\\\"${SESSION}\\\\\",\\\\\"user\\\\\":null}}\"]"}
```

The next line in that playback file is:
```
{"type":"WS_RECV","created":"2017-12-12T22:23:13.916Z","message":"a[\"2#0|m|{\\\\\"custom\\\\\":{\\\\\"shinyjs-onevent\\\\\":{\\\\\"event\\\\\":\\\\\"click\\\\\",\\\\\"id\\\\\":\\\\\"NCAL\\\\\",\\\\\"shinyInputId\\\\\":\\\\\"shinyjs-NCAL-841759203-input-click\\\\\",\\\\\"add\\\\\":false}}}\"]"}
```

That WS_RECV line above has to do with an onClick event using ShinyJS. Could this be the culprit?

**Comment by bogdanrau** [comment]
I just realized that this issue is similar to what https://github.com/rstudio/proxyrec/issues/11 turned into. You can close this if you think they are identical, although #11's title suggest a different initial issue.
