### ISSUE TITLE
Error when trying to record and play the sample app in shiny server

### ISSUE THREAD

**Issue by shalutiwari** [rstudio/proxyrec#14]
WARN [Thread-1] 2018-01-22 12:58:48,794 (Events.kt:68) - REQ_SINF failed (line: 19)
java.lang.IllegalStateException: Status 404 received, expected 200, Response body: 404 Error: Page not found
, URL: http://192.168.41.2:3838/sample-apps/hello/__sockjs__/n%3D81f8b2b7d1f00cfcce/t%3D891a8e0b7049270220c13e429cf5c6e5/w%3D8cad1e528eb7ec0d3d812de28f16bac79dd716c2d37a9ce0/s%3D0/info
	at com.rstudio.proxyrec.Event$Http.get(Events.kt:138)
	at com.rstudio.proxyrec.Event$Http$REQ_SINF$handle$1.invoke(Events.kt:179)
	at com.rstudio.proxyrec.Event$Http$REQ_SINF$handle$1.invoke(Events.kt:173)
	at com.rstudio.proxyrec.Event.tryLog(Events.kt:65)
	at com.rstudio.proxyrec.Event$Http$REQ_SINF.handle(Events.kt:179)
	at com.rstudio.proxyrec.ShinySession.run(Main.kt:149)
	at com.rstudio.proxyrec.LoadTest$run$3.invoke(Main.kt:244)
	at com.rstudio.proxyrec.LoadTest$run$3.invoke(Main.kt:206)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by shalutiwari** [comment]
Still seeing the above error after setting reconnect to true in shiny-server.config file.
